### ISSUE TITLE
Not fully working with all Laravel features (like Markdown emails)

### ISSUE THREAD

**Issue by alexjoffroy** [webwizo/laravel-shortcodes#32]
Replacing `Illuminate\Contracts\View\Engine` by `Illuminate\View\Engines\CompilerEngine` in `src/View/View.php` in PR #30 does not fully working with some part of Laravel, like Markdown emails. 

I'm not sure why this has to be done, because `Illuminate\View\Engines\CompilerEngine` implements `Illuminate\Contracts\View\Engine` ?

https://github.com/webwizo/laravel-shortcodes/blob/b1c88a57977a14892ae483ef8a4306b55a202315/src/View/View.php#L29

**Comment by alexjoffroy** [comment]
Here's the error I get.
```
[2018-06-07 07:49:06] local.ERROR: Type error: Argument 2 passed to Webwizo\Shortcodes\View\View::__construct() must be an instance of Illuminate\View\Engines\CompilerEngine, instance of Illuminate\View\Engines\FileEngine given, called in /code/my-project/vendor/webwizo/laravel-shortcodes/src/View/Factory.php on line 52 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Type error: Argument 2 passed to Webwizo\\Shortcodes\\View\\View::__construct() must be an instance of Illuminate\\View\\Engines\\CompilerEngine, instance of Illuminate\\View\\Engines\\FileEngine given, called in /code/my-project/vendor/webwizo/laravel-shortcodes/src/View/Factory.php on line 52 at /code/my-project/vendor/webwizo/laravel-shortcodes/src/View/View.php:29)
[stacktrace]
#0 /code/my-project/vendor/webwizo/laravel-shortcodes/src/View/Factory.php(52): Webwizo\\Shortcodes\\View\\View->__construct(Object(Webwizo\\Shortcodes\\View\\Factory), Object(Illuminate\\View\\Engines\\FileEngine), 'mail::themes.de...', '/code/...', Array, Object(Webwizo\\Shortcodes\\Compilers\\ShortcodeCompiler))
#1 /code/my-project/vendor/laravel/framework/src/Illuminate/Mail/Markdown.php(64): Webwizo\\Shortcodes\\View\\Factory->make('mail::themes.de...')
#2 /code/my-project/vendor/laravel/framework/src/Illuminate/Mail/Mailable.php(248): Illuminate\\Mail\\Markdown->render('emails.contact', Array)
.....
```
